# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# function for PS1 to display [ git branch] when it is defined
show_git_branch() {
  branch=`__git_ps1`
  PS1="\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]Tiga> \[\033[33m\]\w\[\033[36m\]$branch\[\033[0m\] [\t]\n\[\033[35m\]⚙ ✈ 囍 \[\033[0m\]"
}

export GIT_PS1_SHOWDIRTYSTATE=true

PROMPT_COMMAND="show_git_branch;$PROMPT_COMMAND"
